name: GitHub Actions S3
on: [push]
jobs:
  UpdatePortfolio:
      timeout-minutes: 5
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Upload S3    
          uses: shallwefootball/s3-upload-action@master
          id: S3
          with:
            aws_key_id: ${{secrets.AWS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_bucket: emanzek.co
            source_dir: ''
            destination_dir: ''
        - name: Status upload
          if: success()
          run: echo "Files successfully uploaded!"